### ISSUE TITLE
Missing License file

### ISSUE THREAD

**Issue by yasarcelep** [hepsiburada/VoltranJS#3]
Hi,

Thanks for sharing, it's really good for community. :) 

License file seems missing. 
This project looks like proprietary software, there is no license. :( That might be law issue, we don't know what we have rights about the VoltranJS. Nobody can use or contribute this software because of this reason.

If you want to make it free software("free" as in "free speech," not as in "free beer"; "free" means "özgür" in Turkish) , you have to choose a free license. Or you can choose any other license which one is fit yours. :) 

*https://www.gnu.org/licenses/license-list.en.html

**Comment by volkantagal** [comment]
We are using MTI license.
Anymore everyone can use.. :) 

Thanks for the response.

**Comment by puskuruk** [comment]
<img width="825" alt="Screen Shot 2020-12-31 at 23 32 42" src="https://user-images.githubusercontent.com/22892227/103424992-7c87a300-4bc0-11eb-8fad-2ee040f1d2c1.png">

`Anymore everyone can use... :)` -> Really?..

You can use the links below for finding the best license for your needs:

- [https://www.gnu.org/licenses/license-list.en.html](https://www.gnu.org/licenses/license-list.en.html)
- [https://choosealicense.com](https://choosealicense.com)
