### ISSUE TITLE
Vue JS - Angular Örnekleri

### ISSUE THREAD

**Issue by berataras** [hepsiburada/VoltranJS#41]
Sadece react ile kullanım örneği verilmiş. Bence güzel framework ama readme detaylandırılmalı. Vue, Angular, React ile aynı anda kullanımı nasıl yapacağız? Bir örnek olursa çok iyi olur.

**Comment by emreyalvac** [comment]
Selam,

VoltranJS, suanlik sadece React ekosisteminde calisan bir framework. Planlarimiz ve gereksinim neticesinde diger altyapilara da uygulanabilir elbette.

Zaman ayirdiginiz icin cok tesekkur ederiz @berataras
